name: Sync Fork Main on Issue Opened

on:
  issues:
    types: [opened]

jobs:
  sync_fork:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue title
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          if [[ ! "$ISSUE_TITLE" =~ ^\[N\]- ]]; then
            echo "Issue title does not match the required format. Exiting..."
            exit 0
          fi
        shell: bash
      
      - name: Checkout original repository's main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "ash-hun"
          git config user.email "jhchoi09@naver.com"

      - name: Add fork remote with PAT
        run: |
          git remote add local https://x-access-token:${{ secrets.FORK_GITHUB_TOKEN_JH }}@github.com/ash-hun/infra_test.git
      
      - name: Pull latest changes from origin
        env:
            FORK_GITHUB_TOKEN_JH: ${{ secrets.FORK_GITHUB_TOKEN_JH }}
        run: |
          git pull --rebase https://${FORK_GITHUB_TOKEN_JH}@github.com/ash-hun/infra_test.git main
      
      - name: Debug PAT
        run: |
          if [[ -z "${FORK_GITHUB_TOKEN_JH}" ]]; then
            echo "FORK_GITHUB_TOKEN_JH is empty!"
            exit 1
          else
            echo "FORK_GITHUB_TOKEN_JH is set and has length: ${#FORK_GITHUB_TOKEN_JH}"
          fi
        env:
          FORK_GITHUB_TOKEN_JH: ${{ secrets.FORK_GITHUB_TOKEN_JH }}
      
      - name: Push changes to fork's main branch
        env:
          FORK_GITHUB_TOKEN_JH: ${{ secrets.FORK_GITHUB_TOKEN_JH }}
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
          
          NEW_BRANCH="issue-${SAFE_TITLE:0:30}-${ISSUE_NUMBER}"

          echo "Creating new branch: $NEW_BRANCH"
          git checkout -b "$NEW_BRANCH"
          git push https://ash-hun:${FORK_GITHUB_TOKEN_JH}@github.com/ash-hun/infra_test.git "$NEW_BRANCH"
          echo "Pushed to new branch: $NEW_BRANCH"
